### ISSUE TITLE
Hello, this code still seems to have some bugs? When I run some epochs, it will prompt that models is None in aggregate_models() function.

### ISSUE THREAD

**Issue by xiaobingbuhuitou** [borja-sc/fed-ensemble#1]
First of all, hidden_size needs to be added to the input parameters of the initialization model. Then in the training function should be models_in_ensemble = list(itertools.repeat(Model, num_models_in_ensemble))? Finally, when the aggregation is updated, it prompts that models is None and I don't know how to modify it.

**Comment by borja-sc** [comment]
Hi @xiaobingbuhuitou, thank you for finding out and reporting it!

Indeed it contained some bugs. Main problem was a miscalculation in the aggregate_models() function. 
Let me know if it is now fixed for you. It works for me.

Sorry for the mess, had to refactor some parts before creating the repo and couldn't test it properly.
